// Sample jobs data for testing — remove after finalizing design
export const sampleJobs = [
  {
    job_id: "j001",
    title: "Senior Frontend Engineer",
    company_name: "Google",
    location: "Mountain View, CA",
    experience: "5+ years",
    salary: "$180k - $250k",
    key_skills: ["React", "TypeScript", "Next.js", "GraphQL", "Tailwind CSS", "Node.js"],
    job_url: "https://example.com/job/001",
    posted_at: "2 hours ago",
    job_description: "Build scalable frontend applications using React and TypeScript.",
    source: "LinkedIn",
    relevance_score: "95%",
  },
  {
    job_id: "j002",
    title: "Full Stack Developer",
    company_name: "Meta",
    location: "Menlo Park, CA",
    experience: "3-5 years",
    salary: "$160k - $220k",
    key_skills: ["React", "Python", "PostgreSQL", "Docker"],
    job_url: "https://example.com/job/002",
    posted_at: "5 hours ago",
    job_description: "Develop full-stack features for social media platform.",
    source: "Indeed",
    relevance_score: "92%",
  },
  {
    job_id: "j003",
    title: "Backend Engineer - Distributed Systems",
    company_name: "Amazon",
    location: "Seattle, WA",
    experience: "4+ years",
    salary: "$170k - $240k",
    key_skills: ["Java", "AWS", "Microservices", "Kafka", "DynamoDB"],
    job_url: "https://example.com/job/003",
    posted_at: "1 day ago",
    job_description: "Design and build distributed backend systems at scale.",
    source: "LinkedIn",
    relevance_score: "88%",
  },
  {
    job_id: "j004",
    title: "React Native Developer",
    company_name: "Spotify",
    location: "Stockholm, Sweden",
    experience: "2-4 years",
    salary: "",
    key_skills: ["React Native", "TypeScript", "Redux", "Jest"],
    job_url: "https://example.com/job/004",
    posted_at: "3 hours ago",
    job_description: "Build cross-platform mobile experiences for music streaming.",
    source: "Glassdoor",
    relevance_score: "85%",
  },
  {
    job_id: "j005",
    title: "Machine Learning Engineer",
    company_name: "OpenAI",
    location: "San Francisco, CA",
    experience: "3+ years",
    salary: "$200k - $350k",
    key_skills: ["Python", "PyTorch", "TensorFlow", "NLP", "Transformers", "CUDA"],
    job_url: "https://example.com/job/005",
    posted_at: "6 hours ago",
    job_description: "Research and deploy state-of-the-art ML models.",
    source: "LinkedIn",
    relevance_score: "78%",
  },
  {
    job_id: "j006",
    title: "DevOps Engineer",
    company_name: "Netflix",
    location: "",
    experience: "4-6 years",
    salary: "$165k - $230k",
    key_skills: ["Kubernetes", "Terraform", "CI/CD", "AWS", "Go"],
    job_url: "https://example.com/job/006",
    posted_at: "1 day ago",
    job_description: "Manage cloud infrastructure and deployment pipelines.",
    source: "",
    relevance_score: "90%",
  },
  {
    job_id: "j007",
    title: "iOS Developer",
    company_name: "Apple",
    location: "Cupertino, CA",
    experience: "3+ years",
    salary: "",
    key_skills: ["Swift", "SwiftUI", "UIKit", "Core Data"],
    job_url: "https://example.com/job/007",
    posted_at: "12 hours ago",
    job_description: "Build native iOS applications for Apple ecosystem.",
    source: "Apple Careers",
    relevance_score: "82%",
  },
  {
    job_id: "j008",
    title: "Data Engineer",
    company_name: "Airbnb",
    location: "San Francisco, CA",
    experience: "2-5 years",
    salary: "$150k - $200k",
    key_skills: ["Python", "Spark", "Airflow", "SQL", "dbt"],
    job_url: "https://example.com/job/008",
    posted_at: "2 days ago",
    job_description: "Build and maintain data pipelines for analytics.",
    source: "LinkedIn",
    relevance_score: "87%",
  },
  {
    job_id: "j009",
    title: "Security Engineer",
    company_name: "CrowdStrike",
    location: "Austin, TX",
    experience: "5+ years",
    salary: "$155k - $210k",
    key_skills: ["Security", "Python", "Cloud Security", "SIEM"],
    job_url: "https://example.com/job/009",
    posted_at: "4 hours ago",
    job_description: "Protect enterprise infrastructure from cyber threats.",
    source: "Indeed",
    relevance_score: "74%",
  },
  {
    job_id: "j010",
    title: "Product Designer",
    company_name: "Figma",
    location: "Remote",
    experience: "3-5 years",
    salary: "$140k - $190k",
    key_skills: ["Figma", "UI/UX", "Prototyping", "Design Systems"],
    job_url: "https://example.com/job/010",
    posted_at: "1 day ago",
    job_description: "Design intuitive product experiences for design tools.",
    source: "Glassdoor",
    relevance_score: "70%",
  },
  {
    job_id: "j011",
    title: "Staff Software Engineer",
    company_name: "Stripe",
    location: "San Francisco, CA",
    experience: "7+ years",
    salary: "$220k - $350k",
    key_skills: ["Ruby", "Go", "Distributed Systems", "API Design", "PostgreSQL"],
    job_url: "https://example.com/job/011",
    posted_at: "8 hours ago",
    job_description: "Lead technical architecture for payment infrastructure.",
    source: "LinkedIn",
    relevance_score: "93%",
  },
  {
    job_id: "j012",
    title: "Android Developer",
    company_name: "Samsung",
    location: "Seoul, South Korea",
    experience: "2-4 years",
    salary: "",
    key_skills: ["Kotlin", "Jetpack Compose", "Android SDK"],
    job_url: "https://example.com/job/012",
    posted_at: "3 days ago",
    job_description: "Develop Android applications for Samsung devices.",
    source: "",
    relevance_score: "76%",
  },
  {
    job_id: "j013",
    title: "Cloud Solutions Architect",
    company_name: "Microsoft",
    location: "Redmond, WA",
    experience: "6+ years",
    salary: "$190k - $280k",
    key_skills: ["Azure", "Cloud Architecture", "Terraform", "Kubernetes", "Networking"],
    job_url: "https://example.com/job/013",
    posted_at: "5 hours ago",
    job_description: "Design enterprise cloud solutions on Azure platform.",
    source: "Microsoft Careers",
    relevance_score: "84%",
  },
  {
    job_id: "j014",
    title: "Frontend Developer",
    company_name: "Vercel",
    location: "Remote",
    experience: "2-3 years",
    salary: "$130k - $170k",
    key_skills: ["Next.js", "React", "TypeScript", "Vercel"],
    job_url: "https://example.com/job/014",
    posted_at: "1 hour ago",
    job_description: "Build the future of frontend development tools.",
    source: "LinkedIn",
    relevance_score: "96%",
  },
  {
    job_id: "j015",
    title: "Blockchain Developer",
    company_name: "Coinbase",
    location: "Remote",
    experience: "3+ years",
    salary: "$175k - $250k",
    key_skills: ["Solidity", "Ethereum", "Web3.js", "Smart Contracts"],
    job_url: "https://example.com/job/015",
    posted_at: "2 days ago",
    job_description: "Build decentralized applications and smart contracts.",
    source: "Indeed",
    relevance_score: "68%",
  },
  {
    job_id: "j016",
    title: "Platform Engineer",
    company_name: "Datadog",
    location: "New York, NY",
    experience: "4-6 years",
    salary: "$170k - $230k",
    key_skills: ["Go", "Kubernetes", "Prometheus", "Terraform", "Linux"],
    job_url: "https://example.com/job/016",
    posted_at: "10 hours ago",
    job_description: "Build and scale the observability platform.",
    source: "LinkedIn",
    relevance_score: "81%",
  },
  {
    job_id: "j017",
    title: "QA Automation Engineer",
    company_name: "Atlassian",
    location: "Sydney, Australia",
    experience: "2-4 years",
    salary: "",
    key_skills: ["Selenium", "Cypress", "JavaScript", "CI/CD"],
    job_url: "https://example.com/job/017",
    posted_at: "1 day ago",
    job_description: "Build automated testing frameworks for Jira and Confluence.",
    source: "Glassdoor",
    relevance_score: "72%",
  },
  {
    job_id: "j018",
    title: "AI Research Scientist",
    company_name: "DeepMind",
    location: "London, UK",
    experience: "PhD + 2 years",
    salary: "",
    key_skills: ["Python", "Deep Learning", "Reinforcement Learning", "JAX", "Research"],
    job_url: "https://example.com/job/018",
    posted_at: "4 days ago",
    job_description: "Conduct cutting-edge AI research to solve hard problems.",
    source: "LinkedIn",
    relevance_score: "65%",
  },
  {
    job_id: "j019",
    title: "Site Reliability Engineer",
    company_name: "Uber",
    location: "San Francisco, CA",
    experience: "3-5 years",
    salary: "$160k - $220k",
    key_skills: ["Python", "Go", "Kubernetes", "Monitoring", "Incident Response"],
    job_url: "https://example.com/job/019",
    posted_at: "7 hours ago",
    job_description: "Ensure reliability and uptime for ride-sharing platform.",
    source: "Indeed",
    relevance_score: "83%",
  },
  {
    job_id: "j020",
    title: "Technical Program Manager",
    company_name: "Tesla",
    location: "Palo Alto, CA",
    experience: "5+ years",
    salary: "$150k - $200k",
    key_skills: ["Project Management", "Agile", "Cross-Functional", "Roadmapping"],
    job_url: "https://example.com/job/020",
    posted_at: "2 days ago",
    job_description: "Drive complex engineering programs across teams.",
    source: "",
    relevance_score: "60%",
  },
  {
    job_id: "j021",
    title: "Rust Systems Developer",
    company_name: "Cloudflare",
    location: "Remote",
    experience: "3+ years",
    salary: "$160k - $220k",
    key_skills: ["Rust", "Systems Programming", "Networking", "WebAssembly"],
    job_url: "https://example.com/job/021",
    posted_at: "9 hours ago",
    job_description: "Build high-performance edge computing systems in Rust.",
    source: "LinkedIn",
    relevance_score: "77%",
  },
  {
    job_id: "j022",
    title: "Database Administrator",
    company_name: "Oracle",
    location: "Austin, TX",
    experience: "4-6 years",
    salary: "$130k - $175k",
    key_skills: ["Oracle DB", "SQL", "Performance Tuning", "Backup & Recovery"],
    job_url: "https://example.com/job/022",
    posted_at: "3 days ago",
    job_description: "Manage and optimize enterprise database systems.",
    source: "Indeed",
    relevance_score: "58%",
  },
  {
    job_id: "j023",
    title: "Vue.js Frontend Developer",
    company_name: "GitLab",
    location: "Remote",
    experience: "2-4 years",
    salary: "$120k - $165k",
    key_skills: ["Vue.js", "JavaScript", "GraphQL", "Ruby on Rails"],
    job_url: "https://example.com/job/023",
    posted_at: "1 day ago",
    job_description: "Build frontend features for the DevOps platform.",
    source: "GitLab Careers",
    relevance_score: "79%",
  },
  {
    job_id: "j024",
    title: "Embedded Software Engineer",
    company_name: "NVIDIA",
    location: "Santa Clara, CA",
    experience: "3-5 years",
    salary: "$155k - $215k",
    key_skills: ["C", "C++", "RTOS", "GPU", "CUDA"],
    job_url: "https://example.com/job/024",
    posted_at: "6 hours ago",
    job_description: "Develop firmware and drivers for GPU hardware.",
    source: "LinkedIn",
    relevance_score: "71%",
  },
  {
    job_id: "j025",
    title: "Technical Writer",
    company_name: "Twilio",
    location: "Remote",
    experience: "2+ years",
    salary: "$100k - $140k",
    key_skills: ["Technical Writing", "API Documentation", "Markdown", "REST APIs"],
    job_url: "https://example.com/job/025",
    posted_at: "2 days ago",
    job_description: "Create developer documentation and API guides.",
    source: "Glassdoor",
    relevance_score: "55%",
  },
  {
    job_id: "j026",
    title: "Engineering Manager",
    company_name: "Shopify",
    location: "Ottawa, Canada",
    experience: "7+ years",
    salary: "$185k - $260k",
    key_skills: ["Leadership", "Ruby", "React", "System Design", "Mentoring"],
    job_url: "https://example.com/job/026",
    posted_at: "14 hours ago",
    job_description: "Lead a team of engineers building commerce solutions.",
    source: "LinkedIn",
    relevance_score: "86%",
  },
  {
    job_id: "j027",
    title: "Computer Vision Engineer",
    company_name: "Waymo",
    location: "Mountain View, CA",
    experience: "3+ years",
    salary: "$180k - $260k",
    key_skills: ["Python", "OpenCV", "PyTorch", "Computer Vision", "LiDAR"],
    job_url: "https://example.com/job/027",
    posted_at: "1 day ago",
    job_description: "Develop perception systems for autonomous vehicles.",
    source: "LinkedIn",
    relevance_score: "73%",
  },
  {
    job_id: "j028",
    title: "Go Backend Developer",
    company_name: "Docker",
    location: "Remote",
    experience: "3-5 years",
    salary: "$145k - $195k",
    key_skills: ["Go", "Docker", "gRPC", "Kubernetes", "PostgreSQL"],
    job_url: "https://example.com/job/028",
    posted_at: "18 hours ago",
    job_description: "Build containerization tools and platform services.",
    source: "Indeed",
    relevance_score: "80%",
  },
  {
    job_id: "j029",
    title: "Salesforce Developer",
    company_name: "Deloitte",
    location: "Chicago, IL",
    experience: "2-4 years",
    salary: "$110k - $150k",
    key_skills: ["Apex", "Lightning", "Salesforce", "Integration"],
    job_url: "https://example.com/job/029",
    posted_at: "5 days ago",
    job_description: "Customize and extend Salesforce CRM for enterprise clients.",
    source: "",
    relevance_score: "",
  },
  {
    job_id: "j030",
    title: "Principal Software Architect",
    company_name: "Adobe",
    location: "San Jose, CA",
    experience: "10+ years",
    salary: "$250k - $380k",
    key_skills: ["Architecture", "Java", "Cloud", "Microservices", "AI/ML", "Leadership"],
    job_url: "https://example.com/job/030",
    posted_at: "3 hours ago",
    job_description: "Define technical vision and architecture for Creative Cloud.",
    source: "LinkedIn",
    relevance_score: "91%",
  },
];
